# Tune 5 binary classifiers

In [1]:
import sys, os
from pathlib import Path
ROOT = next((c for c in [Path.cwd(), *Path.cwd().parents] if (c / "src").is_dir() and (c / "data").is_dir()), Path.cwd())
os.chdir(ROOT); sys.path.insert(0, str(ROOT))
from src.training.tune_hyperparams import main as tune
TASKS = ["env", "soc", "gov", "commitment", "specificity"]
OUTDIR = {"env": "topic_e", "soc": "topic_s", "gov": "topic_g", "commitment": "commitment", "specificity": "specificity"}
N_TRIALS = 30   # pruner cắt trial tệ -> tăng trial vẫn rẻ. Search mới: lr/batch/wd/warmup (bỏ epochs).
print("repo:", ROOT, "| trials/task:", N_TRIALS)

C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

repo: d:\esg-washing | trials/task: 30

## Topic — E / S / G

In [2]:
tune(["--config", "config/train.yml", "--task", "env", "--trials", str(N_TRIALS)])

[I 2026-06-13 09:40:20,109] A new study created in RDB with name: esg_env_hyperopt

Optuna tuning: task=env, trials=30

==================================================
TRIAL 0 [encoder] — {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.015600000000000001, 'warmup_ratio': 0.031198904067240532}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:41:10,610] Trial 0 finished with value: 0.9364517935567542 and parameters: {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.015600000000000001, 'warmup_ratio': 0.031198904067240532}. Best is trial 0 with value: 0.9364517935567542.

Trial 0 -> Macro-F1: 0.9365

==================================================
TRIAL 1 [encoder] — {'learning_rate': 1.097990803659665e-05, 'train_batch_size': 8, 'weight_decay': 0.002, 'warmup_ratio': 0.19398197043239887}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:42:07,505] Trial 1 finished with value: 0.9419981060606061 and parameters: {'learning_rate': 1.097990803659665e-05, 'train_batch_size': 8, 'weight_decay': 0.002, 'warmup_ratio': 0.19398197043239887}. Best is trial 1 with value: 0.9419981060606061.

Trial 1 -> Macro-F1: 0.9420

==================================================
TRIAL 2 [encoder] — {'learning_rate': 3.818145165896868e-05, 'train_batch_size': 8, 'weight_decay': 0.0304, 'warmup_ratio': 0.10495128632644757}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:42:53,761] Trial 2 finished with value: 0.9236554307116105 and parameters: {'learning_rate': 3.818145165896868e-05, 'train_batch_size': 8, 'weight_decay': 0.0304, 'warmup_ratio': 0.10495128632644757}. Best is trial 1 with value: 0.9419981060606061.

Trial 2 -> Macro-F1: 0.9237

==================================================
TRIAL 3 [encoder] — {'learning_rate': 2.0040871876541563e-05, 'train_batch_size': 16, 'weight_decay': 0.0292, 'warmup_ratio': 0.07327236865873835}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:43:29,974] Trial 3 finished with value: 0.9410207029369282 and parameters: {'learning_rate': 2.0040871876541563e-05, 'train_batch_size': 16, 'weight_decay': 0.0292, 'warmup_ratio': 0.07327236865873835}. Best is trial 1 with value: 0.9419981060606061.

Trial 3 -> Macro-F1: 0.9410

==================================================
TRIAL 4 [encoder] — {'learning_rate': 2.083431561152948e-05, 'train_batch_size': 8, 'weight_decay': 0.059300000000000005, 'warmup_ratio': 0.009290082543999545}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:44:47,893] Trial 4 finished with value: 0.9410207029369282 and parameters: {'learning_rate': 2.083431561152948e-05, 'train_batch_size': 8, 'weight_decay': 0.059300000000000005, 'warmup_ratio': 0.009290082543999545}. Best is trial 1 with value: 0.9419981060606061.

Trial 4 -> Macro-F1: 0.9410

==================================================
TRIAL 5 [encoder] — {'learning_rate': 1.0490342405839296e-05, 'train_batch_size': 32, 'weight_decay': 0.097, 'warmup_ratio': 0.18704540359456795}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:44:55,867] Trial 5 pruned.

==================================================
TRIAL 6 [encoder] — {'learning_rate': 4.705707822265697e-05, 'train_batch_size': 16, 'weight_decay': 0.0015, 'warmup_ratio': 0.19332409109521262}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:45:06,514] Trial 6 pruned.

==================================================
TRIAL 7 [encoder] — {'learning_rate': 1.083390162478746e-05, 'train_batch_size': 32, 'weight_decay': 0.0983, 'warmup_ratio': 0.13943117966801888}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:45:14,182] Trial 7 pruned.

==================================================
TRIAL 8 [encoder] — {'learning_rate': 3.041304329269237e-05, 'train_batch_size': 8, 'weight_decay': 0.0675, 'warmup_ratio': 0.13507450675765956}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:45:30,632] Trial 8 pruned.

==================================================
TRIAL 9 [encoder] — {'learning_rate': 1.2938169571207525e-05, 'train_batch_size': 8, 'weight_decay': 0.0587, 'warmup_ratio': 0.0665378951893986}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:45:44,342] Trial 9 pruned.

==================================================
TRIAL 10 [encoder] — {'learning_rate': 2.775305272308564e-05, 'train_batch_size': 16, 'weight_decay': 0.0772, 'warmup_ratio': 0.15210630973467135}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:45:51,487] Trial 10 pruned.

==================================================
TRIAL 11 [encoder] — {'learning_rate': 1.7497876236745954e-05, 'train_batch_size': 16, 'weight_decay': 0.033800000000000004, 'warmup_ratio': 0.07839421123784628}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:45:59,195] Trial 11 pruned.

==================================================
TRIAL 12 [encoder] — {'learning_rate': 1.4806802460755685e-05, 'train_batch_size': 16, 'weight_decay': 0.0005, 'warmup_ratio': 0.05599819505406091}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:46:09,787] Trial 12 pruned.

==================================================
TRIAL 13 [encoder] — {'learning_rate': 2.556573519903787e-05, 'train_batch_size': 16, 'weight_decay': 0.031200000000000002, 'warmup_ratio': 0.09228096789737752}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:46:20,531] Trial 13 pruned.

==================================================
TRIAL 14 [encoder] — {'learning_rate': 1.3062825124629483e-05, 'train_batch_size': 32, 'weight_decay': 0.018500000000000003, 'warmup_ratio': 0.16606077023951143}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:46:28,416] Trial 14 pruned.

==================================================
TRIAL 15 [encoder] — {'learning_rate': 2.33798058559148e-05, 'train_batch_size': 8, 'weight_decay': 0.044500000000000005, 'warmup_ratio': 0.12590807577702381}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:46:58,766] Trial 15 pruned.

==================================================
TRIAL 16 [encoder] — {'learning_rate': 3.29642993441282e-05, 'train_batch_size': 16, 'weight_decay': 0.0193, 'warmup_ratio': 0.0016138589052814983}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:47:09,550] Trial 16 pruned.

==================================================
TRIAL 17 [encoder] — {'learning_rate': 1.7259845779063805e-05, 'train_batch_size': 16, 'weight_decay': 0.01, 'warmup_ratio': 0.10827563877183777}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:47:26,955] Trial 17 pruned.

==================================================
TRIAL 18 [encoder] — {'learning_rate': 1.4491376682347897e-05, 'train_batch_size': 8, 'weight_decay': 0.0473, 'warmup_ratio': 0.03883236586283429}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:47:43,537] Trial 18 pruned.

==================================================
TRIAL 19 [encoder] — {'learning_rate': 2.0955423289233747e-05, 'train_batch_size': 32, 'weight_decay': 0.025500000000000002, 'warmup_ratio': 0.17089351181066953}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:47:55,831] Trial 19 pruned.

==================================================
TRIAL 20 [encoder] — {'learning_rate': 1.0035113867653855e-05, 'train_batch_size': 16, 'weight_decay': 0.0448, 'warmup_ratio': 0.11473243569829787}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:48:09,000] Trial 20 pruned.

==================================================
TRIAL 21 [encoder] — {'learning_rate': 2.0713763482350715e-05, 'train_batch_size': 8, 'weight_decay': 0.08320000000000001, 'warmup_ratio': 0.001631258043748732}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:48:49,190] Trial 21 pruned.

==================================================
TRIAL 22 [encoder] — {'learning_rate': 2.160925704270545e-05, 'train_batch_size': 8, 'weight_decay': 0.0574, 'warmup_ratio': 0.033916081731017}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:49:17,445] Trial 22 pruned.

==================================================
TRIAL 23 [encoder] — {'learning_rate': 1.5182010698093214e-05, 'train_batch_size': 8, 'weight_decay': 0.010700000000000001, 'warmup_ratio': 0.021350259198641572}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:49:33,328] Trial 23 pruned.

==================================================
TRIAL 24 [encoder] — {'learning_rate': 1.2093477535657972e-05, 'train_batch_size': 8, 'weight_decay': 0.036000000000000004, 'warmup_ratio': 0.05755066709669581}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:49:49,171] Trial 24 pruned.

==================================================
TRIAL 25 [encoder] — {'learning_rate': 1.8846880912036694e-05, 'train_batch_size': 8, 'weight_decay': 0.058, 'warmup_ratio': 0.0811999377137798}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:50:54,714] Trial 25 finished with value: 0.9475857970583865 and parameters: {'learning_rate': 1.8846880912036694e-05, 'train_batch_size': 8, 'weight_decay': 0.058, 'warmup_ratio': 0.0811999377137798}. Best is trial 25 with value: 0.9475857970583865.

Trial 25 -> Macro-F1: 0.9476

==================================================
TRIAL 26 [encoder] — {'learning_rate': 1.6448900655308528e-05, 'train_batch_size': 8, 'weight_decay': 0.07830000000000001, 'warmup_ratio': 0.0861347194463575}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:51:10,726] Trial 26 pruned.

==================================================
TRIAL 27 [encoder] — {'learning_rate': 2.4165045164869515e-05, 'train_batch_size': 8, 'weight_decay': 0.0391, 'warmup_ratio': 0.06906326702892693}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:51:26,805] Trial 27 pruned.

==================================================
TRIAL 28 [encoder] — {'learning_rate': 1.8641321026900745e-05, 'train_batch_size': 32, 'weight_decay': 0.0517, 'warmup_ratio': 0.04801569857474746}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:51:34,230] Trial 28 pruned.

==================================================
TRIAL 29 [encoder] — {'learning_rate': 3.5917028212972555e-05, 'train_batch_size': 16, 'weight_decay': 0.0102, 'warmup_ratio': 0.09302827579901878}
==================================================
Loading labels...
Train: 1568, Val: 196
label
0    1058
1     510
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1568.000000
mean       47.084184
std        24.942396
min         8.000000
25%        30.000000
50%        42.000000
75%        57.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:51:44,382] Trial 29 pruned.

Best trial #25 — Macro-F1: 0.9476
Params:
  learning_rate: 1.8846880912036694e-05
  train_batch_size: 8
  weight_decay: 0.058
  warmup_ratio: 0.0811999377137798
Saved to outputs\models\topic_e\best_params_env.json

In [3]:
tune(["--config", "config/train.yml", "--task", "soc", "--trials", str(N_TRIALS)])

[I 2026-06-13 09:54:32,009] A new study created in RDB with name: esg_soc_hyperopt

Optuna tuning: task=soc, trials=30

==================================================
TRIAL 0 [encoder] — {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.015600000000000001, 'warmup_ratio': 0.031198904067240532}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:55:28,909] Trial 0 finished with value: 0.9163865546218488 and parameters: {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.015600000000000001, 'warmup_ratio': 0.031198904067240532}. Best is trial 0 with value: 0.9163865546218488.

Trial 0 -> Macro-F1: 0.9164

==================================================
TRIAL 1 [encoder] — {'learning_rate': 1.097990803659665e-05, 'train_batch_size': 8, 'weight_decay': 0.002, 'warmup_ratio': 0.19398197043239887}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:56:38,262] Trial 1 finished with value: 0.9322011688549938 and parameters: {'learning_rate': 1.097990803659665e-05, 'train_batch_size': 8, 'weight_decay': 0.002, 'warmup_ratio': 0.19398197043239887}. Best is trial 1 with value: 0.9322011688549938.

Trial 1 -> Macro-F1: 0.9322

==================================================
TRIAL 2 [encoder] — {'learning_rate': 3.818145165896868e-05, 'train_batch_size': 8, 'weight_decay': 0.0304, 'warmup_ratio': 0.10495128632644757}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:57:22,039] Trial 2 finished with value: 0.9265295358649789 and parameters: {'learning_rate': 3.818145165896868e-05, 'train_batch_size': 8, 'weight_decay': 0.0304, 'warmup_ratio': 0.10495128632644757}. Best is trial 1 with value: 0.9322011688549938.

Trial 2 -> Macro-F1: 0.9265

==================================================
TRIAL 3 [encoder] — {'learning_rate': 2.0040871876541563e-05, 'train_batch_size': 16, 'weight_decay': 0.0292, 'warmup_ratio': 0.07327236865873835}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 09:57:55,178] Trial 3 finished with value: 0.9322011688549938 and parameters: {'learning_rate': 2.0040871876541563e-05, 'train_batch_size': 16, 'weight_decay': 0.0292, 'warmup_ratio': 0.07327236865873835}. Best is trial 1 with value: 0.9322011688549938.

Trial 3 -> Macro-F1: 0.9322

==================================================
TRIAL 4 [encoder] — {'learning_rate': 2.083431561152948e-05, 'train_batch_size': 8, 'weight_decay': 0.059300000000000005, 'warmup_ratio': 0.009290082543999545}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:59:03,894] Trial 4 finished with value: 0.9265295358649789 and parameters: {'learning_rate': 2.083431561152948e-05, 'train_batch_size': 8, 'weight_decay': 0.059300000000000005, 'warmup_ratio': 0.009290082543999545}. Best is trial 1 with value: 0.9322011688549938.

Trial 4 -> Macro-F1: 0.9265

==================================================
TRIAL 5 [encoder] — {'learning_rate': 1.0490342405839296e-05, 'train_batch_size': 32, 'weight_decay': 0.097, 'warmup_ratio': 0.18704540359456795}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:59:11,707] Trial 5 pruned.

==================================================
TRIAL 6 [encoder] — {'learning_rate': 4.705707822265697e-05, 'train_batch_size': 16, 'weight_decay': 0.0015, 'warmup_ratio': 0.19332409109521262}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:59:22,842] Trial 6 pruned.

==================================================
TRIAL 7 [encoder] — {'learning_rate': 1.083390162478746e-05, 'train_batch_size': 32, 'weight_decay': 0.0983, 'warmup_ratio': 0.13943117966801888}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 09:59:31,879] Trial 7 pruned.

==================================================
TRIAL 8 [encoder] — {'learning_rate': 3.041304329269237e-05, 'train_batch_size': 8, 'weight_decay': 0.0675, 'warmup_ratio': 0.13507450675765956}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:00:05,780] Trial 8 pruned.

==================================================
TRIAL 9 [encoder] — {'learning_rate': 1.2938169571207525e-05, 'train_batch_size': 8, 'weight_decay': 0.0587, 'warmup_ratio': 0.0665378951893986}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:00:37,212] Trial 9 pruned.

==================================================
TRIAL 10 [encoder] — {'learning_rate': 2.775305272308564e-05, 'train_batch_size': 16, 'weight_decay': 0.0772, 'warmup_ratio': 0.15210630973467135}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:00:45,896] Trial 10 pruned.

==================================================
TRIAL 11 [encoder] — {'learning_rate': 1.7497876236745954e-05, 'train_batch_size': 16, 'weight_decay': 0.033800000000000004, 'warmup_ratio': 0.07839421123784628}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:00:53,984] Trial 11 pruned.

==================================================
TRIAL 12 [encoder] — {'learning_rate': 1.4806802460755685e-05, 'train_batch_size': 16, 'weight_decay': 0.0005, 'warmup_ratio': 0.05599819505406091}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:01:02,476] Trial 12 pruned.

==================================================
TRIAL 13 [encoder] — {'learning_rate': 2.556573519903787e-05, 'train_batch_size': 16, 'weight_decay': 0.031200000000000002, 'warmup_ratio': 0.09228096789737752}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:01:10,859] Trial 13 pruned.

==================================================
TRIAL 14 [encoder] — {'learning_rate': 1.3062825124629483e-05, 'train_batch_size': 32, 'weight_decay': 0.018500000000000003, 'warmup_ratio': 0.16606077023951143}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:01:18,381] Trial 14 pruned.

==================================================
TRIAL 15 [encoder] — {'learning_rate': 2.33798058559148e-05, 'train_batch_size': 8, 'weight_decay': 0.044500000000000005, 'warmup_ratio': 0.12590807577702381}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:01:44,133] Trial 15 pruned.

==================================================
TRIAL 16 [encoder] — {'learning_rate': 3.29642993441282e-05, 'train_batch_size': 16, 'weight_decay': 0.0193, 'warmup_ratio': 0.0016138589052814983}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:02:00,831] Trial 16 pruned.

==================================================
TRIAL 17 [encoder] — {'learning_rate': 1.7259845779063805e-05, 'train_batch_size': 16, 'weight_decay': 0.01, 'warmup_ratio': 0.10827563877183777}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:02:09,628] Trial 17 pruned.

==================================================
TRIAL 18 [encoder] — {'learning_rate': 1.4491376682347897e-05, 'train_batch_size': 8, 'weight_decay': 0.0473, 'warmup_ratio': 0.03883236586283429}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:02:31,142] Trial 18 pruned.

==================================================
TRIAL 19 [encoder] — {'learning_rate': 2.0955423289233747e-05, 'train_batch_size': 32, 'weight_decay': 0.025500000000000002, 'warmup_ratio': 0.17089351181066953}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:02:39,539] Trial 19 pruned.

==================================================
TRIAL 20 [encoder] — {'learning_rate': 1.0035113867653855e-05, 'train_batch_size': 16, 'weight_decay': 0.0448, 'warmup_ratio': 0.11473243569829787}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:02:48,941] Trial 20 pruned.

==================================================
TRIAL 21 [encoder] — {'learning_rate': 4.060157283658554e-05, 'train_batch_size': 8, 'weight_decay': 0.0371, 'warmup_ratio': 0.09494905595047604}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:03:34,245] Trial 21 finished with value: 0.9316277717578032 and parameters: {'learning_rate': 4.060157283658554e-05, 'train_batch_size': 8, 'weight_decay': 0.0371, 'warmup_ratio': 0.09494905595047604}. Best is trial 1 with value: 0.9322011688549938.

Trial 21 -> Macro-F1: 0.9316

==================================================
TRIAL 22 [encoder] — {'learning_rate': 4.957843366330697e-05, 'train_batch_size': 8, 'weight_decay': 0.0373, 'warmup_ratio': 0.08443423794010749}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:03:46,602] Trial 22 pruned.

==================================================
TRIAL 23 [encoder] — {'learning_rate': 4.053390251259042e-05, 'train_batch_size': 8, 'weight_decay': 0.010700000000000001, 'warmup_ratio': 0.05203566724482791}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:04:05,387] Trial 23 pruned.

==================================================
TRIAL 24 [encoder] — {'learning_rate': 3.551793807896495e-05, 'train_batch_size': 8, 'weight_decay': 0.023700000000000002, 'warmup_ratio': 0.028251856486381163}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:04:31,961] Trial 24 pruned.

==================================================
TRIAL 25 [encoder] — {'learning_rate': 1.215109999846006e-05, 'train_batch_size': 8, 'weight_decay': 0.0551, 'warmup_ratio': 0.0687944902431204}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:04:58,734] Trial 25 pruned.

==================================================
TRIAL 26 [encoder] — {'learning_rate': 2.1676975441129817e-05, 'train_batch_size': 8, 'weight_decay': 0.0398, 'warmup_ratio': 0.09431584594775147}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:05:18,327] Trial 26 pruned.

==================================================
TRIAL 27 [encoder] — {'learning_rate': 1.55780074198753e-05, 'train_batch_size': 8, 'weight_decay': 0.0085, 'warmup_ratio': 0.15510303055508462}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:05:29,789] Trial 27 pruned.

==================================================
TRIAL 28 [encoder] — {'learning_rate': 4.3341015810494675e-05, 'train_batch_size': 32, 'weight_decay': 0.0517, 'warmup_ratio': 0.18070178037816176}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:05:37,606] Trial 28 pruned.

==================================================
TRIAL 29 [encoder] — {'learning_rate': 1.8829869399707898e-05, 'train_batch_size': 16, 'weight_decay': 0.0717, 'warmup_ratio': 0.022630302889302414}
==================================================
Loading labels...
Train: 1590, Val: 199
label
0    955
1    635
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1590.000000
mean       49.244654
std        24.352507
min        11.000000
25%        33.000000
50%        45.000000
75%        60.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:06:02,873] Trial 29 finished with value: 0.9265295358649789 and parameters: {'learning_rate': 1.8829869399707898e-05, 'train_batch_size': 16, 'weight_decay': 0.0717, 'warmup_ratio': 0.022630302889302414}. Best is trial 1 with value: 0.9322011688549938.

Trial 29 -> Macro-F1: 0.9265

Best trial #1 — Macro-F1: 0.9322
Params:
  learning_rate: 1.097990803659665e-05
  train_batch_size: 8
  weight_decay: 0.002
  warmup_ratio: 0.19398197043239887
Saved to outputs\models\topic_s\best_params_soc.json

In [4]:
tune(["--config", "config/train.yml", "--task", "gov", "--trials", str(N_TRIALS)])

[I 2026-06-13 10:06:38,960] A new study created in RDB with name: esg_gov_hyperopt

Optuna tuning: task=gov, trials=30

==================================================
TRIAL 0 [encoder] — {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.015600000000000001, 'warmup_ratio': 0.031198904067240532}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:07:25,569] Trial 0 finished with value: 0.8156742405958004 and parameters: {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.015600000000000001, 'warmup_ratio': 0.031198904067240532}. Best is trial 0 with value: 0.8156742405958004.

Trial 0 -> Macro-F1: 0.8157

==================================================
TRIAL 1 [encoder] — {'learning_rate': 1.097990803659665e-05, 'train_batch_size': 8, 'weight_decay': 0.002, 'warmup_ratio': 0.19398197043239887}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:08:05,449] Trial 1 finished with value: 0.8137912204593029 and parameters: {'learning_rate': 1.097990803659665e-05, 'train_batch_size': 8, 'weight_decay': 0.002, 'warmup_ratio': 0.19398197043239887}. Best is trial 0 with value: 0.8156742405958004.

Trial 1 -> Macro-F1: 0.8138

==================================================
TRIAL 2 [encoder] — {'learning_rate': 3.818145165896868e-05, 'train_batch_size': 8, 'weight_decay': 0.0304, 'warmup_ratio': 0.10495128632644757}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:08:45,402] Trial 2 finished with value: 0.8164498289805966 and parameters: {'learning_rate': 3.818145165896868e-05, 'train_batch_size': 8, 'weight_decay': 0.0304, 'warmup_ratio': 0.10495128632644757}. Best is trial 2 with value: 0.8164498289805966.

Trial 2 -> Macro-F1: 0.8164

==================================================
TRIAL 3 [encoder] — {'learning_rate': 2.0040871876541563e-05, 'train_batch_size': 16, 'weight_decay': 0.0292, 'warmup_ratio': 0.07327236865873835}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:09:26,530] Trial 3 finished with value: 0.8415366146458583 and parameters: {'learning_rate': 2.0040871876541563e-05, 'train_batch_size': 16, 'weight_decay': 0.0292, 'warmup_ratio': 0.07327236865873835}. Best is trial 3 with value: 0.8415366146458583.

Trial 3 -> Macro-F1: 0.8415

==================================================
TRIAL 4 [encoder] — {'learning_rate': 2.083431561152948e-05, 'train_batch_size': 8, 'weight_decay': 0.059300000000000005, 'warmup_ratio': 0.009290082543999545}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:10:13,532] Trial 4 finished with value: 0.8325309043591412 and parameters: {'learning_rate': 2.083431561152948e-05, 'train_batch_size': 8, 'weight_decay': 0.059300000000000005, 'warmup_ratio': 0.009290082543999545}. Best is trial 3 with value: 0.8415366146458583.

Trial 4 -> Macro-F1: 0.8325

==================================================
TRIAL 5 [encoder] — {'learning_rate': 4.629493137087979e-05, 'train_batch_size': 16, 'weight_decay': 0.097, 'warmup_ratio': 0.11060186773569741}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:10:22,578] Trial 5 pruned.

==================================================
TRIAL 6 [encoder] — {'learning_rate': 2.608526629361661e-05, 'train_batch_size': 32, 'weight_decay': 0.055200000000000006, 'warmup_ratio': 0.08538970289869734}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:10:30,369] Trial 6 pruned.

==================================================
TRIAL 7 [encoder] — {'learning_rate': 1.110035130317885e-05, 'train_batch_size': 16, 'weight_decay': 0.09820000000000001, 'warmup_ratio': 0.1891619439947426}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:10:44,049] Trial 7 pruned.

==================================================
TRIAL 8 [encoder] — {'learning_rate': 1.5694167143281026e-05, 'train_batch_size': 16, 'weight_decay': 0.057800000000000004, 'warmup_ratio': 0.15092932195449052}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:10:56,964] Trial 8 pruned.

==================================================
TRIAL 9 [encoder] — {'learning_rate': 3.0353775114737015e-05, 'train_batch_size': 32, 'weight_decay': 0.0346, 'warmup_ratio': 0.05252530680681436}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:11:10,264] Trial 9 pruned.

==================================================
TRIAL 10 [encoder] — {'learning_rate': 1.5003074799543116e-05, 'train_batch_size': 16, 'weight_decay': 0.0772, 'warmup_ratio': 0.135363611619123}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:11:22,081] Trial 10 pruned.

==================================================
TRIAL 11 [encoder] — {'learning_rate': 2.2779722760799943e-05, 'train_batch_size': 8, 'weight_decay': 0.0517, 'warmup_ratio': 0.0027559179458049145}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:11:46,827] Trial 11 pruned.

==================================================
TRIAL 12 [encoder] — {'learning_rate': 2.020181036934033e-05, 'train_batch_size': 16, 'weight_decay': 0.0731, 'warmup_ratio': 0.05599819505406091}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:11:59,725] Trial 12 pruned.

==================================================
TRIAL 13 [encoder] — {'learning_rate': 2.7863223301716718e-05, 'train_batch_size': 8, 'weight_decay': 0.035, 'warmup_ratio': 0.005184721586932264}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:13:26,121] Trial 13 finished with value: 0.8250368188512518 and parameters: {'learning_rate': 2.7863223301716718e-05, 'train_batch_size': 8, 'weight_decay': 0.035, 'warmup_ratio': 0.005184721586932264}. Best is trial 3 with value: 0.8415366146458583.

Trial 13 -> Macro-F1: 0.8250

==================================================
TRIAL 14 [encoder] — {'learning_rate': 1.615196282476727e-05, 'train_batch_size': 32, 'weight_decay': 0.018500000000000003, 'warmup_ratio': 0.059771351140980554}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:13:55,151] Trial 14 finished with value: 0.8359786606580735 and parameters: {'learning_rate': 1.615196282476727e-05, 'train_batch_size': 32, 'weight_decay': 0.018500000000000003, 'warmup_ratio': 0.059771351140980554}. Best is trial 3 with value: 0.8415366146458583.

Trial 14 -> Macro-F1: 0.8360

==================================================
TRIAL 15 [encoder] — {'learning_rate': 1.3628679708362757e-05, 'train_batch_size': 32, 'weight_decay': 0.013600000000000001, 'warmup_ratio': 0.07061368809726973}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:14:05,872] Trial 15 pruned.

==================================================
TRIAL 16 [encoder] — {'learning_rate': 1.675963865196175e-05, 'train_batch_size': 32, 'weight_decay': 0.0193, 'warmup_ratio': 0.039177061305685344}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:14:14,711] Trial 16 pruned.

==================================================
TRIAL 17 [encoder] — {'learning_rate': 1.2284157285923025e-05, 'train_batch_size': 32, 'weight_decay': 0.0267, 'warmup_ratio': 0.09283329920899026}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:14:24,484] Trial 17 pruned.

==================================================
TRIAL 18 [encoder] — {'learning_rate': 3.4037586172884035e-05, 'train_batch_size': 16, 'weight_decay': 0.0004, 'warmup_ratio': 0.12789369325417552}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:14:36,973] Trial 18 pruned.

==================================================
TRIAL 19 [encoder] — {'learning_rate': 2.3500145670012997e-05, 'train_batch_size': 32, 'weight_decay': 0.0425, 'warmup_ratio': 0.07465664519272822}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:14:46,700] Trial 19 pruned.

==================================================
TRIAL 20 [encoder] — {'learning_rate': 1.7968581807290985e-05, 'train_batch_size': 32, 'weight_decay': 0.0439, 'warmup_ratio': 0.04036014859754625}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:14:56,261] Trial 20 pruned.

==================================================
TRIAL 21 [encoder] — {'learning_rate': 2.0204431421603132e-05, 'train_batch_size': 8, 'weight_decay': 0.0687, 'warmup_ratio': 0.02472552764723649}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:15:27,689] Trial 21 pruned.

==================================================
TRIAL 22 [encoder] — {'learning_rate': 2.1911305773304233e-05, 'train_batch_size': 16, 'weight_decay': 0.0852, 'warmup_ratio': 0.06204564989789947}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:15:39,496] Trial 22 pruned.

==================================================
TRIAL 23 [encoder] — {'learning_rate': 1.3899642994749232e-05, 'train_batch_size': 8, 'weight_decay': 0.0092, 'warmup_ratio': 0.01739982215870603}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:17:03,754] Trial 23 finished with value: 0.8379970544918998 and parameters: {'learning_rate': 1.3899642994749232e-05, 'train_batch_size': 8, 'weight_decay': 0.0092, 'warmup_ratio': 0.01739982215870603}. Best is trial 3 with value: 0.8415366146458583.

Trial 23 -> Macro-F1: 0.8380

==================================================
TRIAL 24 [encoder] — {'learning_rate': 1.3472849271586207e-05, 'train_batch_size': 16, 'weight_decay': 0.0076, 'warmup_ratio': 0.02347908368880363}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:17:15,593] Trial 24 pruned.

==================================================
TRIAL 25 [encoder] — {'learning_rate': 1.4441793508853537e-05, 'train_batch_size': 8, 'weight_decay': 0.0218, 'warmup_ratio': 0.05023233850935847}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:17:34,643] Trial 25 pruned.

==================================================
TRIAL 26 [encoder] — {'learning_rate': 1.2464034444894595e-05, 'train_batch_size': 32, 'weight_decay': 0.01, 'warmup_ratio': 0.07540699899032666}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:17:43,677] Trial 26 pruned.

==================================================
TRIAL 27 [encoder] — {'learning_rate': 1.7916267460020378e-05, 'train_batch_size': 16, 'weight_decay': 0.0247, 'warmup_ratio': 0.09360245061678232}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:17:56,267] Trial 27 pruned.

==================================================
TRIAL 28 [encoder] — {'learning_rate': 1.5428145705944382e-05, 'train_batch_size': 32, 'weight_decay': 0.040400000000000005, 'warmup_ratio': 0.04076807942268574}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:18:08,384] Trial 28 pruned.

==================================================
TRIAL 29 [encoder] — {'learning_rate': 1.8348790577695744e-05, 'train_batch_size': 8, 'weight_decay': 0.015600000000000001, 'warmup_ratio': 0.02185966984075733}
==================================================
Loading labels...
Train: 1576, Val: 198
label
0    1154
1     422
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1576.000000
mean       47.208122
std        23.582341
min         8.000000
25%        31.000000
50%        43.000000
75%        58.000000
max       233.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:18:39,543] Trial 29 pruned.

Best trial #3 — Macro-F1: 0.8415
Params:
  learning_rate: 2.0040871876541563e-05
  train_batch_size: 16
  weight_decay: 0.0292
  warmup_ratio: 0.07327236865873835
Saved to outputs\models\topic_g\best_params_gov.json

## Substantiveness — Commitment / Specificity

In [5]:
tune(["--config", "config/train.yml", "--task", "commitment", "--trials", str(N_TRIALS)])

[I 2026-06-13 10:29:27,872] A new study created in RDB with name: esg_commitment_hyperopt

Optuna tuning: task=commitment, trials=30

==================================================
TRIAL 0 [encoder] — {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.0599, 'warmup_ratio': 0.031203728088487304}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:30:25,245] Trial 0 finished with value: 0.9041360294117646 and parameters: {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.0599, 'warmup_ratio': 0.031203728088487304}. Best is trial 0 with value: 0.9041360294117646.

Trial 0 -> Macro-F1: 0.9041

==================================================
TRIAL 1 [encoder] — {'learning_rate': 1.2853916978930139e-05, 'train_batch_size': 16, 'weight_decay': 0.0601, 'warmup_ratio': 0.1416145155592091}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:31:01,704] Trial 1 finished with value: 0.8917937545388526 and parameters: {'learning_rate': 1.2853916978930139e-05, 'train_batch_size': 16, 'weight_decay': 0.0601, 'warmup_ratio': 0.1416145155592091}. Best is trial 0 with value: 0.9041360294117646.

Trial 1 -> Macro-F1: 0.8918

==================================================
TRIAL 2 [encoder] — {'learning_rate': 1.0336843570697396e-05, 'train_batch_size': 8, 'weight_decay': 0.0212, 'warmup_ratio': 0.03636499344142013}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:31:33,738] Trial 2 finished with value: 0.8842163002239796 and parameters: {'learning_rate': 1.0336843570697396e-05, 'train_batch_size': 8, 'weight_decay': 0.0212, 'warmup_ratio': 0.03636499344142013}. Best is trial 0 with value: 0.9041360294117646.

Trial 2 -> Macro-F1: 0.8842

==================================================
TRIAL 3 [encoder] — {'learning_rate': 1.34336568680343e-05, 'train_batch_size': 16, 'weight_decay': 0.0432, 'warmup_ratio': 0.058245828039608386}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:32:22,808] Trial 3 finished with value: 0.9108072017313624 and parameters: {'learning_rate': 1.34336568680343e-05, 'train_batch_size': 16, 'weight_decay': 0.0432, 'warmup_ratio': 0.058245828039608386}. Best is trial 3 with value: 0.9108072017313624.

Trial 3 -> Macro-F1: 0.9108

==================================================
TRIAL 4 [encoder] — {'learning_rate': 2.6771137242145903e-05, 'train_batch_size': 16, 'weight_decay': 0.0366, 'warmup_ratio': 0.0912139968434072}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:33:10,364] Trial 4 finished with value: 0.9044871794871795 and parameters: {'learning_rate': 2.6771137242145903e-05, 'train_batch_size': 16, 'weight_decay': 0.0366, 'warmup_ratio': 0.0912139968434072}. Best is trial 3 with value: 0.9108072017313624.

Trial 4 -> Macro-F1: 0.9045

==================================================
TRIAL 5 [encoder] — {'learning_rate': 4.624859558538402e-05, 'train_batch_size': 16, 'weight_decay': 0.097, 'warmup_ratio': 0.18645806838235746}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:33:20,615] Trial 5 pruned.

==================================================
TRIAL 6 [encoder] — {'learning_rate': 4.7012010241113536e-05, 'train_batch_size': 16, 'weight_decay': 0.0015, 'warmup_ratio': 0.003510347981645394}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:33:31,508] Trial 6 pruned.

==================================================
TRIAL 7 [encoder] — {'learning_rate': 2.6808303486815554e-05, 'train_batch_size': 16, 'weight_decay': 0.09820000000000001, 'warmup_ratio': 0.09341287859877598}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:33:41,422] Trial 7 pruned.

==================================================
TRIAL 8 [encoder] — {'learning_rate': 1.696775705251772e-05, 'train_batch_size': 8, 'weight_decay': 0.0675, 'warmup_ratio': 0.18711237521628496}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:33:53,718] Trial 8 pruned.

==================================================
TRIAL 9 [encoder] — {'learning_rate': 3.0353775114737015e-05, 'train_batch_size': 16, 'weight_decay': 0.037200000000000004, 'warmup_ratio': 0.10363183313286374}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:34:03,837] Trial 9 pruned.

==================================================
TRIAL 10 [encoder] — {'learning_rate': 1.8627452146674586e-05, 'train_batch_size': 8, 'weight_decay': 0.0779, 'warmup_ratio': 0.135363611619123}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:34:40,266] Trial 10 finished with value: 0.883363263802551 and parameters: {'learning_rate': 1.8627452146674586e-05, 'train_batch_size': 8, 'weight_decay': 0.0779, 'warmup_ratio': 0.135363611619123}. Best is trial 3 with value: 0.9108072017313624.

Trial 10 -> Macro-F1: 0.8834

==================================================
TRIAL 11 [encoder] — {'learning_rate': 2.7460193434988528e-05, 'train_batch_size': 16, 'weight_decay': 0.0386, 'warmup_ratio': 0.06855985765326328}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:35:04,119] Trial 11 finished with value: 0.8889716840536512 and parameters: {'learning_rate': 2.7460193434988528e-05, 'train_batch_size': 16, 'weight_decay': 0.0386, 'warmup_ratio': 0.06855985765326328}. Best is trial 3 with value: 0.9108072017313624.

Trial 11 -> Macro-F1: 0.8890

==================================================
TRIAL 12 [encoder] — {'learning_rate': 3.489845103018312e-05, 'train_batch_size': 16, 'weight_decay': 0.038, 'warmup_ratio': 0.06871131571623482}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:35:15,182] Trial 12 pruned.

==================================================
TRIAL 13 [encoder] — {'learning_rate': 2.2249274940005377e-05, 'train_batch_size': 16, 'weight_decay': 0.020800000000000003, 'warmup_ratio': 0.0668251475546987}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:35:24,569] Trial 13 pruned.

==================================================
TRIAL 14 [encoder] — {'learning_rate': 1.3073373071990511e-05, 'train_batch_size': 16, 'weight_decay': 0.048100000000000004, 'warmup_ratio': 0.11949107804491181}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:35:34,503] Trial 14 pruned.

==================================================
TRIAL 15 [encoder] — {'learning_rate': 3.834440338197278e-05, 'train_batch_size': 16, 'weight_decay': 0.022000000000000002, 'warmup_ratio': 0.04550199453554705}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:35:44,590] Trial 15 pruned.

==================================================
TRIAL 16 [encoder] — {'learning_rate': 1.4309060160628173e-05, 'train_batch_size': 16, 'weight_decay': 0.0071, 'warmup_ratio': 0.001174858351586358}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:35:54,644] Trial 16 pruned.

==================================================
TRIAL 17 [encoder] — {'learning_rate': 1.0178437486541458e-05, 'train_batch_size': 16, 'weight_decay': 0.0466, 'warmup_ratio': 0.09044333567610695}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:36:04,063] Trial 17 pruned.

==================================================
TRIAL 18 [encoder] — {'learning_rate': 2.1577663482569866e-05, 'train_batch_size': 8, 'weight_decay': 0.030500000000000003, 'warmup_ratio': 0.16555745189150808}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:36:15,541] Trial 18 pruned.

==================================================
TRIAL 19 [encoder] — {'learning_rate': 2.1817339320839033e-05, 'train_batch_size': 16, 'weight_decay': 0.0781, 'warmup_ratio': 0.05108336771515015}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:36:26,511] Trial 19 pruned.

==================================================
TRIAL 20 [encoder] — {'learning_rate': 1.5190372772934837e-05, 'train_batch_size': 16, 'weight_decay': 0.051500000000000004, 'warmup_ratio': 0.01957296976135045}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:36:37,849] Trial 20 pruned.

==================================================
TRIAL 21 [encoder] — {'learning_rate': 1.733072903563674e-05, 'train_batch_size': 8, 'weight_decay': 0.0585, 'warmup_ratio': 0.035216136217449547}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Training...

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-06-13 10:36:55,529] Trial 21 pruned.

==================================================
TRIAL 22 [encoder] — {'learning_rate': 1.1971235104673359e-05, 'train_batch_size': 8, 'weight_decay': 0.06860000000000001, 'warmup_ratio': 0.0788878858840941}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:37:07,017] Trial 22 pruned.

==================================================
TRIAL 23 [encoder] — {'learning_rate': 2.04037254884797e-05, 'train_batch_size': 8, 'weight_decay': 0.0551, 'warmup_ratio': 0.02240921221759353}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:37:18,122] Trial 23 pruned.

==================================================
TRIAL 24 [encoder] — {'learning_rate': 2.553147002727587e-05, 'train_batch_size': 8, 'weight_decay': 0.041800000000000004, 'warmup_ratio': 0.05077327898896029}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:37:30,537] Trial 24 pruned.

==================================================
TRIAL 25 [encoder] — {'learning_rate': 1.528569585538909e-05, 'train_batch_size': 8, 'weight_decay': 0.027100000000000003, 'warmup_ratio': 0.1093183402757934}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:37:42,376] Trial 25 pruned.

==================================================
TRIAL 26 [encoder] — {'learning_rate': 3.3734740043908165e-05, 'train_batch_size': 8, 'weight_decay': 0.013800000000000002, 'warmup_ratio': 0.02052687807452691}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:37:54,044] Trial 26 pruned.

==================================================
TRIAL 27 [encoder] — {'learning_rate': 2.42201876662945e-05, 'train_batch_size': 16, 'weight_decay': 0.06770000000000001, 'warmup_ratio': 0.058564761663043696}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:38:04,489] Trial 27 pruned.

==================================================
TRIAL 28 [encoder] — {'learning_rate': 1.87550355838188e-05, 'train_batch_size': 8, 'weight_decay': 0.0821, 'warmup_ratio': 0.08441710770205904}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:38:15,957] Trial 28 pruned.

==================================================
TRIAL 29 [encoder] — {'learning_rate': 1.1531404633773272e-05, 'train_batch_size': 16, 'weight_decay': 0.0313, 'warmup_ratio': 0.12597084619507187}
==================================================
Loading labels...
Train: 1341, Val: 149
label
0    773
1    568
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    1341.000000
mean      100.841909
std        70.000504
min         7.000000
25%        54.000000
50%        87.000000
75%       127.000000
max       837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:38:25,846] Trial 29 pruned.

Best trial #3 — Macro-F1: 0.9108
Params:
  learning_rate: 1.34336568680343e-05
  train_batch_size: 16
  weight_decay: 0.0432
  warmup_ratio: 0.058245828039608386
Saved to outputs\models\commitment\best_params_commitment.json

In [6]:
tune(["--config", "config/train.yml", "--task", "specificity", "--trials", str(N_TRIALS)])

[I 2026-06-13 10:38:36,380] A new study created in RDB with name: esg_specificity_hyperopt

Optuna tuning: task=specificity, trials=30

==================================================
TRIAL 0 [encoder] — {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.0599, 'warmup_ratio': 0.031203728088487304}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:38:59,926] Trial 0 finished with value: 0.873728813559322 and parameters: {'learning_rate': 1.827226177606625e-05, 'train_batch_size': 8, 'weight_decay': 0.0599, 'warmup_ratio': 0.031203728088487304}. Best is trial 0 with value: 0.873728813559322.

Trial 0 -> Macro-F1: 0.8737

==================================================
TRIAL 1 [encoder] — {'learning_rate': 1.2853916978930139e-05, 'train_batch_size': 16, 'weight_decay': 0.0601, 'warmup_ratio': 0.1416145155592091}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:39:25,944] Trial 1 finished with value: 0.8883895131086142 and parameters: {'learning_rate': 1.2853916978930139e-05, 'train_batch_size': 16, 'weight_decay': 0.0601, 'warmup_ratio': 0.1416145155592091}. Best is trial 1 with value: 0.8883895131086142.

Trial 1 -> Macro-F1: 0.8884

==================================================
TRIAL 2 [encoder] — {'learning_rate': 1.0336843570697396e-05, 'train_batch_size': 8, 'weight_decay': 0.0212, 'warmup_ratio': 0.03636499344142013}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:39:48,981] Trial 2 finished with value: 0.874438202247191 and parameters: {'learning_rate': 1.0336843570697396e-05, 'train_batch_size': 8, 'weight_decay': 0.0212, 'warmup_ratio': 0.03636499344142013}. Best is trial 1 with value: 0.8883895131086142.

Trial 2 -> Macro-F1: 0.8744

==================================================
TRIAL 3 [encoder] — {'learning_rate': 1.34336568680343e-05, 'train_batch_size': 16, 'weight_decay': 0.0432, 'warmup_ratio': 0.058245828039608386}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:40:15,323] Trial 3 finished with value: 0.8950753485751843 and parameters: {'learning_rate': 1.34336568680343e-05, 'train_batch_size': 16, 'weight_decay': 0.0432, 'warmup_ratio': 0.058245828039608386}. Best is trial 3 with value: 0.8950753485751843.

Trial 3 -> Macro-F1: 0.8951

==================================================
TRIAL 4 [encoder] — {'learning_rate': 2.6771137242145903e-05, 'train_batch_size': 16, 'weight_decay': 0.0366, 'warmup_ratio': 0.0912139968434072}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:40:37,474] Trial 4 finished with value: 0.8817294672456459 and parameters: {'learning_rate': 2.6771137242145903e-05, 'train_batch_size': 16, 'weight_decay': 0.0366, 'warmup_ratio': 0.0912139968434072}. Best is trial 3 with value: 0.8950753485751843.

Trial 4 -> Macro-F1: 0.8817

==================================================
TRIAL 5 [encoder] — {'learning_rate': 4.624859558538402e-05, 'train_batch_size': 16, 'weight_decay': 0.097, 'warmup_ratio': 0.18645806838235746}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:40:45,649] Trial 5 pruned.

==================================================
TRIAL 6 [encoder] — {'learning_rate': 4.7012010241113536e-05, 'train_batch_size': 16, 'weight_decay': 0.0015, 'warmup_ratio': 0.003510347981645394}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:41:07,126] Trial 6 finished with value: 0.8823228803716608 and parameters: {'learning_rate': 4.7012010241113536e-05, 'train_batch_size': 16, 'weight_decay': 0.0015, 'warmup_ratio': 0.003510347981645394}. Best is trial 3 with value: 0.8950753485751843.

Trial 6 -> Macro-F1: 0.8823

==================================================
TRIAL 7 [encoder] — {'learning_rate': 2.6808303486815554e-05, 'train_batch_size': 16, 'weight_decay': 0.09820000000000001, 'warmup_ratio': 0.09341287859877598}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:41:18,173] Trial 7 pruned.

==================================================
TRIAL 8 [encoder] — {'learning_rate': 1.696775705251772e-05, 'train_batch_size': 8, 'weight_decay': 0.0675, 'warmup_ratio': 0.18711237521628496}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:41:27,479] Trial 8 pruned.

==================================================
TRIAL 9 [encoder] — {'learning_rate': 3.0353775114737015e-05, 'train_batch_size': 16, 'weight_decay': 0.037200000000000004, 'warmup_ratio': 0.10363183313286374}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:41:35,504] Trial 9 pruned.

==================================================
TRIAL 10 [encoder] — {'learning_rate': 1.8627452146674586e-05, 'train_batch_size': 8, 'weight_decay': 0.0779, 'warmup_ratio': 0.135363611619123}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:41:44,301] Trial 10 pruned.

==================================================
TRIAL 11 [encoder] — {'learning_rate': 1.0456060129929193e-05, 'train_batch_size': 16, 'weight_decay': 0.0482, 'warmup_ratio': 0.1423955604426824}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:41:52,151] Trial 11 pruned.

==================================================
TRIAL 12 [encoder] — {'learning_rate': 1.3534753697050071e-05, 'train_batch_size': 16, 'weight_decay': 0.0524, 'warmup_ratio': 0.05680797193881017}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:42:00,236] Trial 12 pruned.

==================================================
TRIAL 13 [encoder] — {'learning_rate': 1.3871311528266281e-05, 'train_batch_size': 16, 'weight_decay': 0.07680000000000001, 'warmup_ratio': 0.1501057682655921}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:42:09,868] Trial 13 pruned.

==================================================
TRIAL 14 [encoder] — {'learning_rate': 1.3710573131146042e-05, 'train_batch_size': 16, 'weight_decay': 0.022000000000000002, 'warmup_ratio': 0.06275641562455336}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:42:18,294] Trial 14 pruned.

==================================================
TRIAL 15 [encoder] — {'learning_rate': 1.2144280088416918e-05, 'train_batch_size': 16, 'weight_decay': 0.0356, 'warmup_ratio': 0.12436896677583878}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:42:26,337] Trial 15 pruned.

==================================================
TRIAL 16 [encoder] — {'learning_rate': 2.138645900498798e-05, 'train_batch_size': 16, 'weight_decay': 0.0787, 'warmup_ratio': 0.15892907282241778}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:42:34,568] Trial 16 pruned.

==================================================
TRIAL 17 [encoder] — {'learning_rate': 1.6042484757378383e-05, 'train_batch_size': 16, 'weight_decay': 0.0489, 'warmup_ratio': 0.06832742830137907}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:42:42,740] Trial 17 pruned.

==================================================
TRIAL 18 [encoder] — {'learning_rate': 1.204826519182009e-05, 'train_batch_size': 8, 'weight_decay': 0.0665, 'warmup_ratio': 0.004182713296680782}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:43:18,673] Trial 18 finished with value: 0.8889716840536512 and parameters: {'learning_rate': 1.204826519182009e-05, 'train_batch_size': 8, 'weight_decay': 0.0665, 'warmup_ratio': 0.004182713296680782}. Best is trial 3 with value: 0.8950753485751843.

Trial 18 -> Macro-F1: 0.8890

==================================================
TRIAL 19 [encoder] — {'learning_rate': 2.1817339320839033e-05, 'train_batch_size': 8, 'weight_decay': 0.017, 'warmup_ratio': 0.0025942987644377294}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:43:37,059] Trial 19 finished with value: 0.8817294672456459 and parameters: {'learning_rate': 2.1817339320839033e-05, 'train_batch_size': 8, 'weight_decay': 0.017, 'warmup_ratio': 0.0025942987644377294}. Best is trial 3 with value: 0.8950753485751843.

Trial 19 -> Macro-F1: 0.8817

==================================================
TRIAL 20 [encoder] — {'learning_rate': 1.0011220505843322e-05, 'train_batch_size': 8, 'weight_decay': 0.0901, 'warmup_ratio': 0.021685369242158335}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:43:46,926] Trial 20 pruned.

==================================================
TRIAL 21 [encoder] — {'learning_rate': 1.1965928813108805e-05, 'train_batch_size': 8, 'weight_decay': 0.06470000000000001, 'warmup_ratio': 0.04704011631106922}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:43:55,846] Trial 21 pruned.

==================================================
TRIAL 22 [encoder] — {'learning_rate': 1.50536489328078e-05, 'train_batch_size': 8, 'weight_decay': 0.0567, 'warmup_ratio': 0.073799025119566}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:44:04,695] Trial 22 pruned.

==================================================
TRIAL 23 [encoder] — {'learning_rate': 1.1859267460904103e-05, 'train_batch_size': 8, 'weight_decay': 0.043000000000000003, 'warmup_ratio': 0.1155709623335805}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:44:14,287] Trial 23 pruned.

==================================================
TRIAL 24 [encoder] — {'learning_rate': 1.2093477535657972e-05, 'train_batch_size': 16, 'weight_decay': 0.06910000000000001, 'warmup_ratio': 0.1691173473397221}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:44:22,504] Trial 24 pruned.

==================================================
TRIAL 25 [encoder] — {'learning_rate': 1.4475646499499722e-05, 'train_batch_size': 16, 'weight_decay': 0.0273, 'warmup_ratio': 0.01822432561453856}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:44:30,498] Trial 25 pruned.

==================================================
TRIAL 26 [encoder] — {'learning_rate': 2.0038058425376872e-05, 'train_batch_size': 8, 'weight_decay': 0.0868, 'warmup_ratio': 0.08022863893001765}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:44:40,016] Trial 26 pruned.

==================================================
TRIAL 27 [encoder] — {'learning_rate': 1.6080469039012635e-05, 'train_batch_size': 16, 'weight_decay': 0.060000000000000005, 'warmup_ratio': 0.1980169032901986}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:44:48,215] Trial 27 pruned.

==================================================
TRIAL 28 [encoder] — {'learning_rate': 1.120971369478854e-05, 'train_batch_size': 8, 'weight_decay': 0.0726, 'warmup_ratio': 0.04801569857474746}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:44:58,437] Trial 28 pruned.

==================================================
TRIAL 29 [encoder] — {'learning_rate': 1.3038118661200167e-05, 'train_batch_size': 8, 'weight_decay': 0.0592, 'warmup_ratio': 0.03152900948930221}
==================================================
Loading labels...
Train: 841, Val: 149
label
0    505
1    336
Name: count, dtype: int64

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

count    841.000000
mean     130.555291
std       71.670922
min       22.000000
25%       90.000000
50%      115.000000
75%      152.000000
max      837.000000
Name: sentence, dtype: float64

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Training...

[I 2026-06-13 10:45:42,733] Trial 29 finished with value: 0.8889716840536512 and parameters: {'learning_rate': 1.3038118661200167e-05, 'train_batch_size': 8, 'weight_decay': 0.0592, 'warmup_ratio': 0.03152900948930221}. Best is trial 3 with value: 0.8950753485751843.

Trial 29 -> Macro-F1: 0.8890

Best trial #3 — Macro-F1: 0.8951
Params:
  learning_rate: 1.34336568680343e-05
  train_batch_size: 16
  weight_decay: 0.0432
  warmup_ratio: 0.058245828039608386
Saved to outputs\models\specificity\best_params_specificity.json

## Tổng hợp best params

`03-train-classifiers.ipynb` **tự nạp** `best_params_<task>.json` → KHÔNG cần sửa `config/train.yml` tay. Best params giờ gồm `warmup_ratio` (không còn `epochs`).

In [7]:
import json, pandas as pd
rows = []
for t in TASKS:
    p = ROOT / f"outputs/models/{OUTDIR[t]}/best_params_{t}.json"
    if p.exists():
        rows.append({"task": t, **json.load(open(p))})
    else:
        print("chưa có:", p)
pd.DataFrame(rows)

          task  learning_rate  train_batch_size  weight_decay  warmup_ratio
0          env       0.000019                 8        0.0580      0.081200
1          soc       0.000011                 8        0.0020      0.193982
2          gov       0.000020                16        0.0292      0.073272
3   commitment       0.000013                16        0.0432      0.058246
4  specificity       0.000013                16        0.0432      0.058246